
using System.Windows;
using System.Windows.Controls;

namespace IDCA.Client.View.Helper
{
    public static class DataGridHelper
    {

        public static readonly DependencyProperty ColumnHeaderPaddingProperty =
            DependencyProperty.RegisterAttached(
                "ColumnHeaderPadding",
                typeof(Thickness),
                typeof(DataGridHelper),
                new FrameworkPropertyMetadata(new Thickness(10, 0, 4, 0), FrameworkPropertyMetadataOptions.Inherits));

        [AttachedPropertyBrowsableForType(typeof(DataGrid))]
        public static Thickness GetColumnHeaderPadding(DependencyObject obj)
        {
            return (Thickness)obj.GetValue(ColumnHeaderPaddingProperty);
        }

        [AttachedPropertyBrowsableForType(typeof(DataGrid))]
        public static void SetColumnHeaderPadding(DependencyObject obj, Thickness value)
        {
            obj.SetValue(ColumnHeaderPaddingProperty, value);
        }


        public static readonly DependencyProperty CellPaddingProperty =
            DependencyProperty.RegisterAttached(
                "CellPadding",
                typeof(Thickness),
                typeof(DataGridHelper),
                new FrameworkPropertyMetadata(new Thickness(0), FrameworkPropertyMetadataOptions.Inherits));

        [AttachedPropertyBrowsableForType(typeof(DataGrid))]
        [AttachedPropertyBrowsableForType(typeof(DataGridRow))]
        public static Thickness GetCellPadding(DependencyObject obj)
        {
            return (Thickness)obj.GetValue(CellPaddingProperty);
        }

        [AttachedPropertyBrowsableForType(typeof(DataGrid))]
        [AttachedPropertyBrowsableForType(typeof(DataGridRow))]
        public static void SetCellPadding(DependencyObject obj, Thickness value)
        {
            obj.SetValue(CellPaddingProperty, value);
        }


        public static readonly DependencyProperty AutoGeneratedTextColumnEditingStyleProperty =
            DependencyProperty.RegisterAttached(
                "AutoGeneratedTextColumnEditingStyle",
                typeof(Style),
                typeof(DataGridHelper),
                new PropertyMetadata(default(Style)));

        [AttachedPropertyBrowsableForType(typeof(DataGrid))]
        public static Style? GetAutoGeneratedTextColumnEditingStyle(UIElement element)
        {
            return (Style?)element.GetValue(AutoGeneratedTextColumnEditingStyleProperty);
        }

        [AttachedPropertyBrowsableForType(typeof(DataGrid))]
        public static void SetAutoGeneratedTextColumnEditingStyle(UIElement element, Style? value)
        {
            element.SetValue(AutoGeneratedTextColumnEditingStyleProperty, value);
        }


        public static readonly DependencyProperty AutoGeneratedComboBoxColumnStyleProperty =
            DependencyProperty.RegisterAttached(
                "AutoGeneratedComboBoxColumnStyle",
                typeof(Style),
                typeof(DataGridHelper),
                new PropertyMetadata(default(Style)));

        [AttachedPropertyBrowsableForType(typeof(DataGrid))]
        public static Style? GetAutoGeneratedComboBoxColumnStyle(UIElement element)
        {
            return (Style?)element.GetValue(AutoGeneratedComboBoxColumnStyleProperty);
        }

        [AttachedPropertyBrowsableForType(typeof(DataGrid))]
        public static void SetAutoGeneratedComboBoxColumnStyle(UIElement element, Style? value)
        {
            element.SetValue(AutoGeneratedComboBoxColumnStyleProperty, value);
        }



        public static readonly DependencyProperty AutoGeneratedComboBoxColumnEditingStyleProperty =
            DependencyProperty.RegisterAttached(
                "AutoGeneratedComboBoxColumnEditingStyle",
                typeof(Style),
                typeof(DataGridHelper),
                new PropertyMetadata(default(Style)));

        [AttachedPropertyBrowsableForType(typeof(DataGrid))]
        public static Style? GetAutoGeneratedComboBoxColumnEditingStyle(UIElement element)
        {
            return (Style?)element.GetValue(AutoGeneratedComboBoxColumnEditingStyleProperty);
        }

        [AttachedPropertyBrowsableForType(typeof(DataGrid))]
        public static void SetAutoGeneratedComboBoxColumnEditingStyle(UIElement element, Style? value)
        {
            element.SetValue(AutoGeneratedComboBoxColumnEditingStyleProperty, value);
        }

    }
}
