//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDCA.Client.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GLOBAL_TEMPLATE_ROOTPATH {
            get {
                return ((string)(this["GLOBAL_TEMPLATE_ROOTPATH"]));
            }
            set {
                this["GLOBAL_TEMPLATE_ROOTPATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("V")]
        public string METADATA_CATEGORICAL_LABEL {
            get {
                return ((string)(this["METADATA_CATEGORICAL_LABEL"]));
            }
            set {
                this["METADATA_CATEGORICAL_LABEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Total Respondents")]
        public string AXIS_BASE_LABEL {
            get {
                return ((string)(this["AXIS_BASE_LABEL"]));
            }
            set {
                this["AXIS_BASE_LABEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sigma")]
        public string AXIS_SIGMA_LABEL {
            get {
                return ((string)(this["AXIS_SIGMA_LABEL"]));
            }
            set {
                this["AXIS_SIGMA_LABEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Net.")]
        public string AXIS_NET_AHEAD_LABEL {
            get {
                return ((string)(this["AXIS_NET_AHEAD_LABEL"]));
            }
            set {
                this["AXIS_NET_AHEAD_LABEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AXIS_NET_INSERT_EMPTYLINE {
            get {
                return ((bool)(this["AXIS_NET_INSERT_EMPTYLINE"]));
            }
            set {
                this["AXIS_NET_INSERT_EMPTYLINE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int AXIS_TOP_BOTTOM_BOX_POSITION {
            get {
                return ((int)(this["AXIS_TOP_BOTTOM_BOX_POSITION"]));
            }
            set {
                this["AXIS_TOP_BOTTOM_BOX_POSITION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AXIS_NET_TYPE {
            get {
                return ((int)(this["AXIS_NET_TYPE"]));
            }
            set {
                this["AXIS_NET_TYPE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" - Summary")]
        public string TABLE_SUMMARY_LABEL {
            get {
                return ((string)(this["TABLE_SUMMARY_LABEL"]));
            }
            set {
                this["TABLE_SUMMARY_LABEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int AXIS_NPS_TOP_BOX {
            get {
                return ((int)(this["AXIS_NPS_TOP_BOX"]));
            }
            set {
                this["AXIS_NPS_TOP_BOX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int AXIS_NPS_BOTTOM_BOX {
            get {
                return ((int)(this["AXIS_NPS_BOTTOM_BOX"]));
            }
            set {
                this["AXIS_NPS_BOTTOM_BOX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AXIS_ADD_SIGMA {
            get {
                return ((bool)(this["AXIS_ADD_SIGMA"]));
            }
            set {
                this["AXIS_ADD_SIGMA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Average")]
        public string AXIS_AVERAGE_MENTION_LABEL {
            get {
                return ((string)(this["AXIS_AVERAGE_MENTION_LABEL"]));
            }
            set {
                this["AXIS_AVERAGE_MENTION_LABEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AXIS_AVERAGE_MENTION_BLANKLINE {
            get {
                return ((bool)(this["AXIS_AVERAGE_MENTION_BLANKLINE"]));
            }
            set {
                this["AXIS_AVERAGE_MENTION_BLANKLINE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int AXIS_AVERAGE_MENTION_DECIMALS {
            get {
                return ((int)(this["AXIS_AVERAGE_MENTION_DECIMALS"]));
            }
            set {
                this["AXIS_AVERAGE_MENTION_DECIMALS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(":")]
        public string TABLE_SETTING_NET_LABEL_CODE_SEPARATER {
            get {
                return ((string)(this["TABLE_SETTING_NET_LABEL_CODE_SEPARATER"]));
            }
            set {
                this["TABLE_SETTING_NET_LABEL_CODE_SEPARATER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(",")]
        public string TABLE_SETTING_NET_CODE_SEPARATER {
            get {
                return ((string)(this["TABLE_SETTING_NET_CODE_SEPARATER"]));
            }
            set {
                this["TABLE_SETTING_NET_CODE_SEPARATER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-")]
        public string TABLE_SETTING_NET_RANGE_SEPARATER {
            get {
                return ((string)(this["TABLE_SETTING_NET_RANGE_SEPARATER"]));
            }
            set {
                this["TABLE_SETTING_NET_RANGE_SEPARATER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AVERAGE")]
        public string AXIS_MEAN_LABEL {
            get {
                return ((string)(this["AXIS_MEAN_LABEL"]));
            }
            set {
                this["AXIS_MEAN_LABEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("STANDARD DEVIATION")]
        public string AXIS_STDDEV_LABEL {
            get {
                return ((string)(this["AXIS_STDDEV_LABEL"]));
            }
            set {
                this["AXIS_STDDEV_LABEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("STANDARD ERROR")]
        public string AXIS_STDERR_LABEL {
            get {
                return ((string)(this["AXIS_STDERR_LABEL"]));
            }
            set {
                this["AXIS_STDERR_LABEL"] = value;
            }
        }
    }
}
