//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDCA.Client.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Templates {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Templates"]));
            }
            set {
                this["Templates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("V")]
        public string MetadataCategoricalLabel {
            get {
                return ((string)(this["MetadataCategoricalLabel"]));
            }
            set {
                this["MetadataCategoricalLabel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Total Respondents")]
        public string AxisBaseLabel {
            get {
                return ((string)(this["AxisBaseLabel"]));
            }
            set {
                this["AxisBaseLabel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sigma")]
        public string AxisSigmaLabel {
            get {
                return ((string)(this["AxisSigmaLabel"]));
            }
            set {
                this["AxisSigmaLabel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Net.")]
        public string AxisNetAheadLabel {
            get {
                return ((string)(this["AxisNetAheadLabel"]));
            }
            set {
                this["AxisNetAheadLabel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AxisNetInsertEmptyLine {
            get {
                return ((bool)(this["AxisNetInsertEmptyLine"]));
            }
            set {
                this["AxisNetInsertEmptyLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int AxisTopBottomBoxPositon {
            get {
                return ((int)(this["AxisTopBottomBoxPositon"]));
            }
            set {
                this["AxisTopBottomBoxPositon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AxisCombinePosition {
            get {
                return ((int)(this["AxisCombinePosition"]));
            }
            set {
                this["AxisCombinePosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" - Summary")]
        public string TableSummaryLabel {
            get {
                return ((string)(this["TableSummaryLabel"]));
            }
            set {
                this["TableSummaryLabel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TemplateRootPath {
            get {
                return ((string)(this["TemplateRootPath"]));
            }
            set {
                this["TemplateRootPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int AxisNpsTopBox {
            get {
                return ((int)(this["AxisNpsTopBox"]));
            }
            set {
                this["AxisNpsTopBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int AxisNpsBottomBox {
            get {
                return ((int)(this["AxisNpsBottomBox"]));
            }
            set {
                this["AxisNpsBottomBox"] = value;
            }
        }
    }
}
